language: generic

sudo: false

matrix:
  include:
    - addons:
        apt:
          sources: [ { sourceline: 'ppa:kelleyk/emacs' } ]
          packages: [ emacs25 ]

before_install:
  - export EMACS=/usr/bin/emacs25
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python

install:
  - export PATH=$HOME/.cask/bin:$PATH
  - cask

script:
  - $EMACS --version
  - cask exec ecukes --no-win -r magnars
